app-config:
  thirdParty:
    tongdun: http://master:1280/ace-tongdun
    miguan: http://master:1280/ace-miguan
    hr: http://master:1280/ace-hr
    model: http://master
    python-model-base-url: http:/master
  httpClientProperties:
    connectTimeout: 20000
    requestTimeout: 20000
    socketTimeout: 30000
    defaultMaxPerRoute: 100
    maxTotalConnections: 300
    defaultKeepAliveTimeMillis: 20000
    closeIdleConnectionWaitTimeSecs: 30
dingtalk:
  robot:
    webhook: https://oapi.dingtalk.com/robot/send?access_token={my_token}
server:
  port: 8090
logging:
  path: ./logs/
